image: node:16

cache:
  key: $CI_COMMIT_REF_SLUG
  paths:
    - .npm/
    - node_modules

before_script:
  - npm ci --cache .npm --prefer-offline

variables:
  TURBO_TOKEN: $TURBO_TOKEN
  TURBO_TEAM: $TURBO_TEAM

stages: # List of stages for jobs, and their order of execution
  - test

unit-test-job: # This job runs in the test stage.
  stage: test # It only starts when the job in the build stage completes successfully.
  script:
    - npm run lint
    - npm run test
